name: Vercel Development Deployment (service)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SERVICE }}
on:
  push:
    branches:
      - develop
    paths:
      - 'apps/service/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/service-*.yml'
jobs:
  Deploy-Development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: check pnpm version
        run: pnpm --version
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --cwd apps/service --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --cwd apps/service --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --cwd apps/service --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
